package workspace

import "github.com/axgiroud312-byte/prism-local-browser/internal/kernel"

const FingerprintGeneratorVersion = "windows-local-v1"

// DeviceProfile contains frozen application inputs, never invented hardware
// readings. Parameters are generated by the capability compiler, not the client.
type DeviceProfile struct {
	SchemaVersion        int      `json:"schemaVersion"`
	ConfigRevision       int64    `json:"configRevision"`
	Seed                 string   `json:"seed"`
	TemplateID           string   `json:"templateId"`
	TemplateVersion      string   `json:"templateVersion"`
	GeneratorVersion     string   `json:"generatorVersion"`
	Platform             string   `json:"platform"`
	PlatformVersion      string   `json:"platformVersion"`
	Brand                string   `json:"brand"`
	BrandVersion         string   `json:"brandVersion"`
	KernelID             string   `json:"kernelId"`
	CoreActualVersion    string   `json:"coreActualVersion"`
	CoreExecutableSHA256 string   `json:"coreExecutableSha256"`
	AdapterVersion       string   `json:"adapterVersion"`
	CapabilityVersion    string   `json:"capabilityVersion"`
	Language             string   `json:"language"`
	AcceptLanguages      []string `json:"acceptLanguages"`
	UILanguage           string   `json:"uiLanguage"`
	Timezone             string   `json:"timezone"`
	RegionPreset         string   `json:"regionPreset"`
	CPU                  string   `json:"cpu"`
	Width                int      `json:"width"`
	Height               int      `json:"height"`
	Parameters           []string `json:"parameters"`
	ConfigHash           string   `json:"configHash"`
}
type ProfileChange struct {
	Field  string `json:"field"`
	Before string `json:"before"`
	After  string `json:"after"`
}
type FingerprintReport struct {
	KernelID            string              `json:"kernelId"`
	EvidenceStatus      string              `json:"evidenceStatus"`
	Capabilities        []kernel.Capability `json:"capabilities"`
	ObservedFingerprint *kernel.Observation `json:"observedFingerprint"`
	CanLaunchNative     bool                `json:"canLaunchNative"`
}
type FingerprintPreview struct {
	Mode             string            `json:"mode"`
	PreviewProfile   DeviceProfile     `json:"previewProfile"`
	CapabilityReport FingerprintReport `json:"capabilityReport"`
	Changes          []ProfileChange   `json:"changes"`
	Action           string            `json:"action"`
	RestoredFrom     int64             `json:"restoredFrom,omitempty"`
}
type ProfileRevision struct {
	Profile      DeviceProfile `json:"profile"`
	CreatedAt    string        `json:"createdAt"`
	Action       string        `json:"action"`
	RestoredFrom int64         `json:"restoredFrom,omitempty"`
}
type FingerprintOverrides struct {
	Language string `json:"language"`
	Timezone string `json:"timezone"`
	CPU      string `json:"cpu"`
	Width    int    `json:"width"`
	Height   int    `json:"height"`
}
type GenerateFingerprint struct {
	PreviewID  string               `json:"previewId"`
	KernelID   string               `json:"kernelId"`
	TemplateID string               `json:"templateId"`
	Overrides  FingerprintOverrides `json:"overrides"`
	Regenerate bool                 `json:"regenerate"`
}
