import { useState } from "react";
import { parseProxyText, regions, uid, type ProxyNode } from "../domain";
import type { ApplicationService, ProxyConfiguration, WorkspaceView } from "../application/contract";
import { ProxyManagementPage } from "./ProxyManagementPage";
import { ProxyImportWindow } from "./ProxyImportWindow";
import { ProxyEditWindow } from "./ProxyEditWindow";
import { ProxyUsageWindow } from "./ProxyUsageWindow";
import { ProxyKernelModal } from "./ProxyKernelModal";

export function DemoProxyManager({ application, workspace, checking, onCheck, onImported }: { application: ApplicationService; workspace: WorkspaceView; checking: string[]; onCheck: (ids: string[]) => void; onImported?: (ids: string[]) => void }) {
  const [importOpen, setImportOpen] = useState(false), [importMode, setImportMode] = useState<"text" | "file" | "single">("text"), [editing, setEditing] = useState<ProxyNode>(), [usage, setUsage] = useState<ProxyNode>(), [deleting, setDeleting] = useState<ProxyNode>(), [detail, setDetail] = useState<ProxyNode>();
  const [configuration, setConfiguration] = useState<ProxyConfiguration>(), [credentialAction, setCredentialAction] = useState<"keep" | "replace" | "clear">("keep"), [username, setUsername] = useState(""), [password, setPassword] = useState(""), [simulateFailure, setSimulateFailure] = useState(false), [message, setMessage] = useState("");
  const state = workspace.state;
  function mutate(change: (state: WorkspaceView["state"]) => WorkspaceView["state"], action: string, target: string) {
    const result = application.compatibility?.update(state => { const next = change(state); return { ...next, activities: [{ id: uid("log"), action, target, detail: "演示代理配置操作，不是真实网络验证。", result: "success" as const, time: new Date().toISOString() }, ...next.activities].slice(0, 300) }; });
    if (!result?.ok) { setMessage(result ? `${result.error.code}：${result.error.message}` : "演示服务不可用"); return false; } return true;
  }
  function edit(id: string) { const record = state.proxies.find(proxy => proxy.id === id); if (!record) return; if (state.environments.some(environment => environment.proxyId === id && ["running", "starting", "stopping"].includes(environment.status))) { setMessage("请先关闭使用此代理的环境；没有修改配置。"); return; } setEditing(record); setConfiguration({ name: record.name, type: record.type, host: record.host, port: record.port, country: record.country }); setCredentialAction("keep"); setUsername(""); setPassword(""); setSimulateFailure(!!record.simulateFailure); setMessage(""); }
  function save() {
    if (!editing || !configuration || workspace.issue) return;
    const host = configuration.host.includes(":") && !configuration.host.startsWith("[") ? `[${configuration.host}]` : configuration.host;
    const parsed = parseProxyText(`${configuration.type}://${host}:${configuration.port}`)[0];
    if (!regions[configuration.country]) { setMessage("演示地区需使用 US / GB / DE / JP / SG / CN 中的现有模板；本机地区标签与实测另列。"); return; }
    if (!configuration.name.trim() || !parsed?.node || configuration.host.includes("@") || /[\s/?#]/.test(configuration.host) || !Number.isInteger(configuration.port) || configuration.port < 1 || configuration.port > 65535) { setMessage("请填写有效的名称、主机和端口。"); return; }
    if (!mutate(state => ({ ...state, proxies: state.proxies.map(proxy => proxy.id === editing.id ? { ...proxy, ...configuration, name: configuration.name.trim(), username: credentialAction === "keep" ? proxy.username : credentialAction === "replace" ? username : "", password: credentialAction === "keep" ? proxy.password : credentialAction === "replace" ? password : "", simulateFailure, status: "unchecked", latency: undefined } : proxy) }), "修改代理", configuration.name)) return;
    setEditing(undefined); setConfiguration(undefined); setUsername(""); setPassword(""); setMessage("代理已保存，请重新做示例检查。");
  }
  return <><ProxyManagementPage native={false} records={state.proxies.map(proxy => ({ ...proxy, usedCount: state.environments.filter(environment => environment.proxyId === proxy.id).length, hasAuthentication: !!(proxy.username || proxy.password), busy: checking.includes(proxy.id), statusText: checking.includes(proxy.id) ? "模拟检查中…" : proxy.status === "connected" ? `模拟可连接 · ${proxy.latency ?? "—"}ms` : proxy.status === "failed" ? "模拟连接失败" : "尚未检查", deleteProtected: state.environments.some(environment => environment.proxyId === proxy.id) }))} busy={!!workspace.issue} message={message} onImport={mode => { setImportMode(mode); setImportOpen(true); }} onEdit={edit} onDelete={id => setDeleting(state.proxies.find(proxy => proxy.id === id))} onCheck={onCheck} onUsage={id => setUsage(state.proxies.find(proxy => proxy.id === id))} onDetails={id => setDetail(state.proxies.find(proxy => proxy.id === id))} onRefresh={() => void application.refresh?.()} />
    <ProxyImportWindow application={application} open={importOpen} onClose={() => setImportOpen(false)} initialMode={importMode} onImported={onImported} />
    {editing && configuration && <ProxyEditWindow configuration={configuration} onConfiguration={setConfiguration} credentialAction={credentialAction} onCredentialAction={value => { setUsername(""); setPassword(""); setCredentialAction(value); }} username={username} password={password} onUsername={setUsername} onPassword={setPassword} hasAuthentication={!!(editing.username || editing.password)} native={false} busy={!!workspace.issue} simulateFailure={simulateFailure} onSimulateFailure={setSimulateFailure} message={message} onClose={() => { setEditing(undefined); setConfiguration(undefined); setUsername(""); setPassword(""); }} onSave={save} />}
    {deleting && <ProxyKernelModal title="删除代理确认" width={400} onClose={() => setDeleting(undefined)} footer={<><button className="button" onClick={() => setDeleting(undefined)}>取消</button><button className="button danger" disabled={!!workspace.issue || state.environments.some(environment => environment.proxyId === deleting.id)} onClick={() => { if (mutate(state => ({ ...state, proxies: state.proxies.filter(proxy => proxy.id !== deleting.id) }), "删除代理", deleting.name)) setDeleting(undefined); }}>确认删除</button></>}><p>确定删除 {deleting.name}？被环境引用的节点不能删除，不会静默清空代理绑定。</p>{message && <p role="status">{message}</p>}</ProxyKernelModal>}
    {usage && <ProxyUsageWindow name={usage.name} ids={state.environments.filter(environment => environment.proxyId === usage.id).map(environment => environment.id)} total={state.environments.filter(environment => environment.proxyId === usage.id).length} workspace={workspace} onClose={() => setUsage(undefined)} />}
    {detail && <ProxyKernelModal title={`代理检查详情 · ${detail.name}`} width={620} onClose={() => setDetail(undefined)} footer={<button className="button primary" onClick={() => setDetail(undefined)}>确定</button>}><p>示例检测 · {detail.status === "connected" ? "模拟可连接" : detail.status === "failed" ? "模拟连接失败" : "尚未检查"}</p><p>没有真实出口 IP、认证或阶段观测。失败阻断示例启动，不会自动切换直连。</p></ProxyKernelModal>}</>;
}
