import type { NativeKernel } from "../application/contract";
import type { Kernel } from "../domain";
import { ProxyKernelModal } from "./ProxyKernelModal";

const fields: Record<string, string> = { identity: "品牌和真实版本", seed: "固定种子", cpu: "CPU", acceptLanguages: "网页 / 请求语言", timezone: "时区", uiLanguage: "浏览器菜单语言", memory: "内存", gpu: "GPU / WebGL", "font/canvas/audio/clientrects": "字体 / 绘图 / 音频", "screen/location/webgpu/tls/mac": "屏幕 / 定位 / 其他", "proxy/webrtc": "代理 / WebRTC" };
const statuses = { configurable: "可配置", "seed-generated": "由固定内核按 seed 生成", system: "跟随真实环境", unverified: "未验证 · 不开放编辑" };
export function KernelDetailsWindow({ record, demoRecord, onClose }: { record?: NativeKernel; demoRecord?: Kernel; onClose: () => void }) {
  return <ProxyKernelModal title="内核能力与接入" width={660} variant="drawer" onClose={onClose} className="kernel35-details" footer={<button className="button primary" onClick={onClose}>确定</button>}>
    {record ? <><h3>fingerprint-chromium {record.version}</h3><dl className="kernel35-evidence"><dt>精确 ID</dt><dd>{record.id}</dd><dt>状态 / 架构</dt><dd>{record.status === "verified" ? "真实诊断已核验" : "核验失败 · 不可用"} / {record.architecture}</dd><dt>发行 tag</dt><dd>{record.source.tag}</dd><dt>来源</dt><dd>{record.source.kind === "official" ? "官方发行" : "用户确认可信的本地归档"}<br />{record.source.location}</dd><dt>源码 commit</dt><dd>{record.source.commit ?? "未知，不从 main 推断"}</dd><dt>归档 SHA-256</dt><dd>{record.archiveSha256}</dd><dt>主程序 SHA-256</dt><dd>{record.executableSha256}</dd><dt>内部安装引用</dt><dd>{record.installPath}</dd><dt>关联环境</dt><dd>{record.usedCount ?? record.usedBy.length} 个 · 服务返回 {record.usedBy.length} 个 ID<ul>{record.usedBy.map(id => <li key={id}>{id}</li>)}</ul></dd></dl>
      <h3>查看该版本能力与实测读值</h3><p>{record.report.adapterVersion} · {record.report.version}<br />安装时采样 {record.report.sampledAt} · {record.report.transport} · 沙箱 {record.report.sandbox ? "保留" : "未核实"}</p>
      <table className="pk35-table"><thead><tr><th>字段</th><th>支持状态</th><th>证据来源</th></tr></thead><tbody>{record.report.capabilities.map(capability => <tr key={capability.field}><td>{fields[capability.field] ?? capability.field}<span className="pk35-secondary">{capability.note}</span></td><td>{statuses[capability.status]}</td><td>{capability.source === "observed" ? "observed · 安装时观测" : capability.source === "source-derived" ? "source-derived · 源码推导" : "unverified · 未探测"}</td></tr>)}</tbody></table>
      <div className="pk35-table-scroll"><table className="pk35-table"><thead><tr><th>诊断 seed</th><th>CPU / 语言 / 时区</th><th>实际版本 / 正常退出</th></tr></thead><tbody>{record.report.observations.length ? record.report.observations.map((sample, index) => <tr key={index}><td>{sample.seed}</td><td>{sample.cpu} / {sample.language} / {sample.timezone}</td><td>{sample.browserVersion} / {sample.normalExit ? "是" : "否"}</td></tr>) : <tr><td colSpan={3} className="pk35-empty">没有返回观测；不制造当前环境实测值</td></tr>}</tbody></table></div><p>诊断报告只对应此精确构建的采样；不等于当前环境实际读值。未验证菜单语言、屏幕、定位等不开放任意编辑；正常运行与代理能力按各自验收记录，不将源码推导当已实测。</p>
    </> : <><h3>{demoRecord?.source} {demoRecord?.version}</h3><p>演示元数据 · {demoRecord?.available ? "可选示例基线" : "待验证"}，不是本机已安装。</p><p>{demoRecord?.note}</p><dl className="kernel35-evidence"><dt>可配置输入</dt><dd>固定 seed、网站语言、明确时区、CPU 偏好；属于演示输入，不是真实参数读回。</dd><dt>内核生成</dt><dd>GPU、内存、绘图 / 音频等由内核与 seed 决定。原型不伪造精细控制或实际观测。</dd><dt>未验证</dt><dd>完整屏幕指纹、定位、菜单语言及跨版本兼容性，不开放任意字段编辑。</dd></dl><p>真实接入需要准确版本、来源、归档和主程序哈希，以及该不可变构建的能力记录。原型不会下载或启动内核。</p></>}
  </ProxyKernelModal>;
}
