import { useState, type ReactNode } from "react";
import { ChevronDown, Globe, Pencil, RefreshCw, Search, Trash2 } from "lucide-react";
import { ReferencePopover } from "./ReferenceUi";
import "./proxy-kernel35.css";

export interface ProxyListRecord {
  id: string; name: string; type: "http" | "https" | "socks5"; host: string; port: number; country: string;
  status: "unchecked" | "connected" | "failed"; hasAuthentication: boolean; usedCount: number;
  exitIp?: string; statusText?: string; busy?: boolean; cancelDisabled?: boolean; deleteProtected?: boolean;
}
export interface ProxyManagementPageProps {
  records: ProxyListRecord[]; native: boolean; busy?: boolean; message?: string;
  onImport: (mode: "text" | "file" | "single") => void; onAdd?: () => void; onEdit: (id: string) => void;
  onDelete: (id: string) => void; onCheck: (ids: string[]) => void; onCancelCheck?: (id: string) => void;
  onUsage: (id: string) => void; onDetails?: (id: string) => void; onRefresh?: () => void;
  onAssign?: () => void; children?: ReactNode;
}
export function ProxyManagementPage({ records, native, busy = false, message, onImport, onAdd = () => onImport("single"), onEdit, onDelete, onCheck, onCancelCheck, onUsage, onDetails, onRefresh, onAssign, children }: ProxyManagementPageProps) {
  const [search, setSearch] = useState(""), [filter, setFilter] = useState("all"), [page, setPage] = useState(1), [selected, setSelected] = useState<string[]>([]);
  const [menu, setMenu] = useState<{ anchor: HTMLElement; kind: "add" | "more" }>();
  const filtered = records.filter(record => (!search || `${record.name} ${record.host} ${record.country}`.toLowerCase().includes(search.toLowerCase())) && (filter === "all" || record.status === filter));
  const maxPage = Math.max(1, Math.ceil(filtered.length / 10)), currentPage = Math.min(page, maxPage), items = filtered.slice((currentPage - 1) * 10, currentPage * 10);
  const selectedIds = selected.filter(id => records.some(record => record.id === id));
  const checkIds = selectedIds.length ? selectedIds : filtered.map(record => record.id);
  return <div className="proxy35-page pk35-page">
    <div className="pk35-tabs"><span className="selected">代理 IP 管理</span><span className="pk35-mode">{native ? "本机配置 · 凭据不回显" : "演示配置 · 检测均为模拟"}</span></div>
    <section className="pk35-list-panel" aria-label="代理列表">
      <div className="pk35-toolbar"><div className="pk35-split"><button className="button primary" disabled={busy} onClick={onAdd ?? (() => onImport("text"))}>添加代理</button><button className="button primary" aria-label="代理添加方式" disabled={busy} onClick={event => setMenu({ anchor: event.currentTarget, kind: "add" })}><ChevronDown size={12} /></button></div><button className="button primary" disabled={busy || !checkIds.length} onClick={() => onCheck([...checkIds])}>批量代理检测</button><label className="pk35-search"><input aria-label="搜索代理" placeholder="输入名称 / 地址 / 地区" value={search} onChange={event => { setSearch(event.target.value); setPage(1); }} /><Search size={15} /></label><select aria-label="代理检查状态" value={filter} onChange={event => { setFilter(event.target.value); setPage(1); }}><option value="all">全部状态</option><option value="unchecked">尚未检查</option><option value="connected">本次通过</option><option value="failed">检查失败</option></select><span className="pk35-toolbar-tail" /><button className="button primary" disabled={busy} onClick={() => onImport("text")}>批量添加代理</button><button className="button primary" disabled={busy} onClick={event => setMenu({ anchor: event.currentTarget, kind: "more" })}>更多操作<ChevronDown size={12} /></button></div>
      <div className="pk35-table-scroll"><table className="pk35-table proxy35-table"><thead><tr><th><input aria-label="选择当前页全部代理" type="checkbox" checked={items.length > 0 && items.every(record => selectedIds.includes(record.id))} onChange={event => setSelected(previous => event.target.checked ? [...new Set([...previous, ...items.map(record => record.id)])] : previous.filter(id => !items.some(record => record.id === id)))} /></th><th>代理类型</th><th>代理信息</th><th>出口 IP / 检查</th><th>绑定环境</th><th>认证</th><th>地区</th><th>名称</th><th>操作</th></tr></thead><tbody>{items.length ? items.map(record => <tr key={record.id}><td><input aria-label={`选择代理 ${record.name}`} type="checkbox" checked={selectedIds.includes(record.id)} onChange={event => setSelected(previous => event.target.checked ? [...previous, record.id] : previous.filter(id => id !== record.id))} /></td><td><span className="proxy35-protocol">{record.type === "socks5" ? "S" : "H"}</span>{record.type.toUpperCase()}</td><td className="pk35-wrap">{record.host.includes(":") && !record.host.startsWith("[") ? `[${record.host}]` : record.host}:{record.port}</td><td><button className={`pk35-link ${record.status === "failed" ? "pk35-danger" : ""}`} onClick={() => onDetails?.(record.id)} disabled={!onDetails}>{record.statusText ?? (record.status === "connected" ? native ? "本次检查通过" : "模拟可连接" : record.status === "failed" ? native ? "检查未通过" : "模拟连接失败" : "尚未检查")}</button>{record.exitIp && <span className="pk35-secondary">{record.exitIp}</span>}</td><td><button className="pk35-link" aria-label={`${record.name} 已绑定环境`} onClick={() => onUsage(record.id)}><Globe size={14} />{record.usedCount}</button></td><td>{record.hasAuthentication ? "已设置（遮罩）" : "无认证"}</td><td>{record.country || "—"}</td><td>{record.name}</td><td><div className="pk35-row-actions"><button className="pk35-link" disabled={busy || record.busy} onClick={() => onCheck([record.id])}>检查</button>{record.busy && onCancelCheck && <button className="pk35-link" disabled={busy || record.cancelDisabled} onClick={() => onCancelCheck(record.id)}>取消检查</button>}<button className="icon-button" aria-label={`编辑代理 ${record.name}`} disabled={busy || record.busy} onClick={() => onEdit(record.id)}><Pencil size={15} /></button><button className="icon-button pk35-danger" aria-label={`删除代理 ${record.name}`} title={record.deleteProtected ? "先修改引用环境的绑定" : "删除代理配置"} disabled={busy || record.busy || record.deleteProtected} onClick={() => onDelete(record.id)}><Trash2 size={15} /></button></div></td></tr>) : <tr><td colSpan={9} className="pk35-empty">{records.length ? "没有匹配代理，可清除筛选。" : native ? "没有本机代理，演示记录不会进入这里。" : "还没有代理，可添加示例配置。"}</td></tr>}</tbody></table></div>
      <div className="pk35-pagination"><span>共 {filtered.length} 条</span><span>10条/页</span><button disabled={currentPage <= 1} aria-label="上一页代理" onClick={() => setPage(currentPage - 1)}>‹</button><span className="pk35-current-page">{currentPage}</span><button disabled={currentPage >= maxPage} aria-label="下一页代理" onClick={() => setPage(currentPage + 1)}>›</button><span>前往</span><input aria-label="代理页码" type="number" min={1} max={maxPage} value={currentPage} onChange={event => setPage(Math.max(1, Math.min(maxPage, Number(event.target.value) || 1)))} /><span>页</span>{selectedIds.length > 0 && <button className="pk35-link" onClick={() => setSelected([])}>取消已选 {selectedIds.length} 项</button>}</div>
      <p className="pk35-page-boundary">{native ? "独立检查只反映本次临时通道；环境启动仍重新核对自己的通道与隔离资源。全路径及人工桌面验收仍待补。" : "示例检测不访问网络、不启动真实内核。"} 失败不自动改为直连，不保证永久保护。</p>
      {message && <p role="status" className="pk35-message">{message}</p>}{children}
    </section>
    {menu && !busy && <ReferencePopover anchor={menu.anchor} label={menu.kind === "add" ? "代理添加方式" : "代理更多操作"} onClose={() => setMenu(undefined)}>{menu.kind === "add" ? <><button role="menuitem" onClick={() => { setMenu(undefined); onAdd ? onAdd() : onImport("text"); }}>添加单个代理</button><button role="menuitem" onClick={() => { setMenu(undefined); onImport("text"); }}>批量文本导入</button><button role="menuitem" onClick={() => { setMenu(undefined); onImport("file"); }}>导入文本文件</button></> : <>{onRefresh && <button role="menuitem" onClick={() => { setMenu(undefined); onRefresh(); }}><RefreshCw size={14} />重新读取</button>}{onAssign && <button role="menuitem" onClick={() => { setMenu(undefined); onAssign(); }}>批量分配代理</button>}<button role="menuitem" onClick={() => { setMenu(undefined); setSearch(""); setFilter("all"); setPage(1); }}>清除筛选</button></>}</ReferencePopover>}
  </div>;
}
